import sys
print(f"python {sys.version}")
import tensorflow
print(f"tensorflow {tensorflow.__version__}")
import keras
print(f"keras {keras.__version__}")
import sklearn
print(f"sklearn {sklearn.__version__}")
import skimage
print(f"skimage {skimage.__version__}")
import pandas
print(f"pandas {pandas.__version__}")
import polars
print(f"polars {polars.__version__}")
import jax
print(f"jax {jax.__version__}")
import flax
print(f"flax {flax.__version__}")
import PIL
print(f"PIL {PIL.__version__}")
import seaborn
print(f"seaborn {seaborn.__version__}")
import matplotlib
print(f"matplotlib {matplotlib.__version__}")
import torch
print(f"torch {torch.__version__}")
import torchaudio
print(f"torchaudio {torchaudio.__version__}")
import torchgen
print(f"torchgen present, version unknown")
import torchvision
print(f"torchvision {torchvision.__version__}")
