# Makefile - builds the deeplearning_1.0.sif container.

deeplearning_2024.2.0.sif: Singularity.deeplearning
	rm -f $@
	sudo `which singularity` build --disable-cache --nv $@ $<

clean:
	rm -f *.sif slurm-*.out
